required = [
    "k8s.io/client-go/plugin/pkg/client/auth/gcp"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/kubernetes"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/client-go"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/apimachinery"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/api"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "k8s.io/helm"
  version = "2.13.1"

# Fix google.org/protobuf
# https://github.com/google/protobuf/issues/4582
# Override Helm version with the closest release version
[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "11.3.0-beta"

# matching client go dependency
[[constraint]]
  name = "github.com/Azure/go-autorest"
  revision = "bca49d5b51a50dc5bb17bbf6204c711c6dbded06"

# matching client go dependency
[[constraint]]
  name = "github.com/ghodss/yaml"
  revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"

# matching client go dependency
[[constraint]] 
  name = "github.com/pmezard/go-difflib"
  revision = "d8ed2627bdf02c080bf22230dbb337003b7aba2d"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "=0.5.2"

# https://github.com/kubernetes/client-go#compatibility-matrix
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.11.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "9be88ef10da45f8260fac1eafa747a2898949f51"

[[override]]
  name = "k8s.io/utils"
  revision = "011bbbe3b2878d9b1d484312f186826acd7e78cc"

# unknown field 'CaseSensitive' in struct literal of type jsoniter.Config
[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"
[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.13.1"
